name: faiadashu_example
description: Gallery app for Faiadashuâ„¢

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  collection: ^1.16.0

  faiadashu:
    path: ..

  faiadashu_online:
    path: ../faiadashu_online

  fhir: ^0.11.0
#  fhir:
#    path: /Users/tilo/Projects/fhir/fhir

  fhir_auth: ^0.11.0-dev.1
#  fhir_auth:
#    path: ../../fhir/fhir_auth

  file: ^6.1.4

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^4.0.4

  intl: ^0.18.0

  logging: ^1.0.2

  simple_html_css: ^4.0.0

dev_dependencies:
  lint: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/instruments/
    - assets/valuesets/
    - assets/codesystems/
    - assets/responses/
    - assets/images/
