name: faiadashu_example
description: Gallery app for Faiadashuâ„¢

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  collection: ^1.16.0

  faiadashu:
    path: ..

  faiadashu_online:
    path: ../faiadashu_online

  fhir: ^0.8.0
#  fhir:
#    path: /Users/tilo/Projects/fhir/fhir

  fhir_auth: ^0.8.0
#  fhir_auth:
#    path: ../../fhir/fhir_auth

  file: ^6.1.4

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^4.0.4

  intl: ^0.18.0

  logging: ^1.0.2

  simple_html_css: ^3.0.1+1

dev_dependencies:
  lint: ^1.8.2


flutter:
  uses-material-design: true

  assets:
    - assets/instruments/
    - assets/valuesets/
    - assets/codesystems/
    - assets/responses/
    - assets/images/
